site_name: AI wiki

repo_name: ai-self-learning
repo_url: https://github.com/Axi404/ai-self-learning/

copyright: Copyright &copy; 2024-present <a href="https://github.com/Axi404" target="_blank" rel="noopener noreferrer">Axi404</a>

theme:
  name: material
  language: zh
  static_templates:
    - 404.html
  include_search_page: false
  search_index_only: true

  features:
    - header.autohide
    - navigation.tracking
    - navigation.top
    - search.highlight
    - search.share
    - search.suggest
    - content.code.annotate

  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: light blue
      accent: deep purple
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: cyan
      accent: deep purple
      toggle:
        icon: material/weather-night
        name: Switch to light mode

  font:
    text: 'Times New Roman'
    code: 'Fira Code'
  icon:
    repo: fontawesome/brands/github

extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/Axi404

plugins:
  - search:
      lang:
        - zh
        - en

markdown_extensions:
  - attr_list
  - md_in_html
  - footnotes

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/pkuflyingpig/cs-self-learning/
  analytics:
    provider: google
    property: G-KJB4RXSKZG

nav:
  - 前言: "index.md"
  - 常识:
      - 课题组: "常识/课题组.md"
      - 顶刊与顶会: "常识/顶刊与顶会.md"
      - 名词对照表: "常识/名词对照表.md"
  - 知识图谱:
      - 基础知识: "知识图谱/基础知识.md"
      - 机器学习: "知识图谱/机器学习.md"
      - 深度学习: "知识图谱/深度学习.md"
  - 科研技巧:
      - 前言: "科研技巧/前言.md"
      - 思维模式: "科研技巧/思维模式.md"
      - Idea选择: "科研技巧/Idea选择.md"
      - 论文阅读: "科研技巧/论文阅读.md"